GET https://integration-api-6cas.onrender.com/auth/login/success
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3A1AdIg8UFMT8RnItUBBpkYFRrb71ltCE5.KydNuBbu2NiQFZjInAZvAgbQUZW%2B8wiZALTW%2FWvxHlo
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET http://localhost:3001/auth/login/success
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3ASmnggXqGnjnor9BLKbQA0ywa3swQht_-.CXfWJnNKOD6fVoCnJILETDWy7igOP2KqBPK7uDw5B%2Fo
Host: localhost:3001
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET /auth/login/success HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3AxGOwTNXloAvD-s7zTMozFyr211LVEEZE.ZghAF30XkkwvbELAhDi2FdtdgguPD1lHPTwO2%2BRMRZ8
Host: localhost:3001
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
GET http://localhost:3001/api/characterLocations/

###
GET http://localhost:3001/api/scores/

###
POST http://localhost:3001/api/characterLocations/
content-type: application/json

{
    "puzzle": "puzzle3",
    "charName": "King Boo",
    "xMin": 23.34,
    "xMax": 32.9,
    "yMin": 50.23,
    "yMax": 56.64
}

###
POST http://localhost:3001/api/scores/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzBlZDIzODg2ZDMzMzI0NjcyN2QwNSIsImlhdCI6MTY5NzcwNTQ3MywiZXhwIjoxNjk3NzA5MDczfQ.ZEMCxKrc9KyzW8OtkjXzIKrWTlwuP3-Buq_Ycnb42mY

{
    "puzzle": "puzzle1",
    "seconds": 421
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "displayName": "Vincenzo ",
    "password": "12345678",
    "email": "vincent@gmail.com",
    "source": "local",
    "isVerified": true
}

###
GET http://localhost:3001/hello?person=%3Cb%3EJohn%3C/b%3E

###
GET http://localhost:3001/hello?person=<b>john</b>

###
GET http://localhost:3001/api/login-local/success
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzBlZDhiODg2ZDMzMzI0NjcyN2QwZCIsImlhdCI6MTY5NzcwNTQxMCwiZXhwIjoxNjk3NzA5MDEwfQ.SvSQGgRbC9WStVDFFv_PBIP9GM9ONhAsL3jRKHvFEYE

###
GET http://localhost:3001/api/verify-email/?token=$2b$10$bGdf1GZ6JfSZrFyRVceWueHYE7qHYAfjsGezPkQuU/I.OFEBdNbf6

###
POST http://localhost:3001/api/login-local/
content-type: application/json

{
    "email": "vincent@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3001/api/login-local/
content-type: application/json

{
    "email": "jace@gmail.com",
    "password": "12345678"
}


###
GET http://localhost:3001/api/send-verification-email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MWVhNzFmZmI0NDEyMmUzNzdlNDQzMSIsImlhdCI6MTY5NjUxNTI0NywiZXhwIjoxNjk2NTE4ODQ3fQ.HC_eh1t4rOXIxp_Z7qrKDmgpM9gmTSCbjquxI6mHMDY




# ###
# GET http://localhost:3001/info/

# ###
# GET  http://localhost:3001/api/persons/1

# ###
# GET  http://localhost:3001/api/persons/64d63c45e3583a8cc2dd1ba8

# ###
# DELETE http://localhost:3001/api/persons/64d63c1eb5a442d2a637326f

###
PUT http://localhost:3001/api/users/655984f9cdf54644327b89ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk4NGY5Y2RmNTQ2NDQzMjdiODlhYiIsImlhdCI6MTcwMDYzMTQyNiwiZXhwIjoxNzAwODA0MjI2fQ.uZLrhTrI4ig0G-g1C0mJZibop8LMSsO8L92bTkihlic
content-type: application/json

{
    "displayName":"Lyra",
    "bio": "angel, dawnbringer",
    "gender": "female",
    "worksAt": "Copiose degusto cibus victus cursim. Aperiam deduco vigor supellex tergeo voveo. Ocer dapifer contego coepi angelus ventus esse uter aequitas."
}

###
GET http://localhost:3001/api/users/655d78a0e1ed1d25add769dc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMDk3MjgwNiwiZXhwIjoxNzAxMTQ1NjA2fQ.3ItFeKW8kVlveCJdyazl2b_BoUZoiU5LUqe4lUTOTnU

###
POST http://localhost:3001/api/uploadImage
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

[Binary content of your image file]
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST /api/profile HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 199
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryflwK7GEET1hwhvic
Cookie: connect.sid=s%3ATlwVQuDvy6O6ZyhU7BJeEoAyrQ3qF4Jf.%2Baqr3KqDXnvzdYXtjUOQDVZnOhOnsM04oM0BC42cIeo
Host: localhost:3001
Origin: http://localhost:5173
Pragma: no-cache
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

------WebKitFormBoundaryflwK7GEET1hwhvic
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

[Binary content of your image file]
------WebKitFormBoundaryflwK7GEET1hwhvic--

###
POST /api/profile HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 198
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryGjHkJDVBrdZE0PK8
Cookie: connect.sid=s%3ATlwVQuDvy6O6ZyhU7BJeEoAyrQ3qF4Jf.%2Baqr3KqDXnvzdYXtjUOQDVZnOhOnsM04oM0BC42cIeo
Host: localhost:3001
Origin: http://localhost:5173
Pragma: no-cache
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

###
POST http://localhost:3001/api/profile-delete
content-type: application/json

{
    "filePath": "uploads/image-1697105229252-520621196.jpg"
}

### 
POST http://localhost:3001/api/friend-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk4NTVhY2RmNTQ2NDQzMjdiODllNSIsImlhdCI6MTcwMDM2NTg5MCwiZXhwIjoxNzAwNTM4NjkwfQ.U1irKkZKAP_efSU22aDGwSvDnUaxEoZazKxqWI7FfZQ
content-type: application/json

{
    "toUserId": "655974b5aa661554a4e17eb5"
}


### 
POST http://localhost:3001/api/friend-requests/6551af488dc715fc810930a4/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTY5OTg1MjIzMCwiZXhwIjoxNzAwMDI1MDMwfQ.mfKSa54An-yWYP1lN7efkVjKYODBaU9X1y4MvfXCooU
content-type: application/json

# ###
# 653a4afd85af1aba6865b64a pius
# 653a4b0a85af1aba6865b64f rens
# 653a4b2385af1aba6865b653 renelyn
# 653b8caaac0a2c39713d78ad jace

###
GET  http://localhost:3001/api/users

###
POST http://localhost:3001/api/login-local/
content-type: application/json

{
    "email": "jace@gmail.com",
    "password": "12345678"
}


###
PUT http://localhost:3001/api/friend-requests/655d78a0e1ed1d25add769dc/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMDk3MjgwNiwiZXhwIjoxNzAxMTQ1NjA2fQ.3ItFeKW8kVlveCJdyazl2b_BoUZoiU5LUqe4lUTOTnU

###
Pius
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YWZkODVhZjFhYmE2ODY1YjY0YSIsImlhdCI6MTY5ODQxMDE5NSwiZXhwIjoxNjk4NDk2NTk1fQ.6H3nmepbAIggqVKojzfFqZ2nJqUR6FLJK0Aqwz9jwX8
Anoyo
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YjBhODVhZjFhYmE2ODY1YjY0ZiIsImlhdCI6MTY5ODQxMTk3MywiZXhwIjoxNjk4NDk4MzczfQ.8qTgd83AK-R00IwXEzaooQLbkc930CqYAXyai-FTWk8
Renelyn
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YjIzODVhZjFhYmE2ODY1YjY1MyIsImlhdCI6MTY5ODQxODEzMiwiZXhwIjoxNjk4NTA0NTMyfQ.wDFrBZBhpuvm6Y_iYUcH_w0N1N61v0jkmTa7TgvrxOk
Jace
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2I4Y2FhYWMwYTJjMzk3MTNkNzhhZCIsImlhdCI6MTY5ODQxODMwMCwiZXhwIjoxNjk4NTA0NzAwfQ.CwErYQ2zXIaT1B50Zcuu1e3aFSyVaMBIrQBjmYcR_L0

###
GET http://localhost:3001/api/users/eligible-friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMDcxMTcyOSwiZXhwIjoxNzAwODg0NTI5fQ.RBKWBkuTdgq7JTWpvK_XtPVE7H3OaX1AJ_9pC__oAIY

###
GET http://localhost:3001/api/users/pending-friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMDg2OTMwOSwiZXhwIjoxNzAxMDQyMTA5fQ.mDI2WolQNj6NsvwBrf6hMnbAP_sMoXNh4imMFrhT988

###
GET http://localhost:3001/api/users/incoming-friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMDg2OTMwOSwiZXhwIjoxNzAxMDQyMTA5fQ.mDI2WolQNj6NsvwBrf6hMnbAP_sMoXNh4imMFrhT988

####
GET http://localhost:3001/api/users/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMTI0MDMyOSwiZXhwIjoxNzAxNDEzMTI5fQ.HeczAbJ1EE1fZK1-9pYO6eFLLYcz0z6JxjgLWFP7TIQ

###
GET http://localhost:3001/api/users/6550b31b9738cb8925aeb966/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMTI0MDMyOSwiZXhwIjoxNzAxNDEzMTI5fQ.HeczAbJ1EE1fZK1-9pYO6eFLLYcz0z6JxjgLWFP7TIQ


###
GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMTE0NzIzNiwiZXhwIjoxNzAxMzIwMDM2fQ.1n1HEWW7XBm70mHFQ_G4OcXVSggPfj0PGVH_hYr_cdE

###
GET http://localhost:3001/api/posts-of-friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMTE0NzIzNiwiZXhwIjoxNzAxMzIwMDM2fQ.1n1HEWW7XBm70mHFQ_G4OcXVSggPfj0PGVH_hYr_cdE

###
GET http://localhost:3001/api/posts-of-self
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YWZkODVhZjFhYmE2ODY1YjY0YSIsImlhdCI6MTY5OTQxOTA4MCwiZXhwIjoxNjk5Njc4MjgwfQ.uNxsGPLhWVq7IHWKNtltopTDkcealAeuFgkCdYEuw1A

###
GET http://localhost:3001/api/posts-of-self
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YjIzODVhZjFhYmE2ODY1YjY1MyIsImlhdCI6MTY5OTYxNjE5NSwiZXhwIjoxNjk5Nzg4OTk1fQ.Dr7b7uBCSOLC8udZk7dIZEOl_mhROFv8blhO2HK2jN0

###
GET http://localhost:3001/api/users/6550b31b9738cb8925aeb966/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMTIzODcwMCwiZXhwIjoxNzAxNDExNTAwfQ.khTHeSOOgCcbbxVYc3IbWzcEj9NwE24bbId4kRk_gZk

###
DELETE http://localhost:3001/api/posts/655974d6aa661554a4e17ee8/comments/65597654aa661554a4e17f65
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMDM3Mzk4OSwiZXhwIjoxNzAwNTQ2Nzg5fQ.6bFMuEv5Ke3iy-ucoCAmrU2DXMsB8_CdPTGDeI2EFCE

# GET /api/posts/:postId/comments
# POST /api/posts/:postId/comments
# DELETE /api/posts/:postId/comments/:commentId


###
POST http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiMzFiOTczOGNiODkyNWFlYjk2NiIsImlhdCI6MTcwMDAzMTk3MCwiZXhwIjoxNzAwMjA0NzcwfQ.hSwBsLunRqasEp707vWZSlaJIf6ladW9uEKq4TfTwh8
content-type: application/json

{
    "content": "Goodluck!"
}

###
PATCH http://localhost:3001/api/posts/654c416cba2b802c82c1d218/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YWZkODVhZjFhYmE2ODY1YjY0YSIsImlhdCI6MTY5OTc1NTMxOSwiZXhwIjoxNjk5OTI4MTE5fQ.6poFg-5NQprUU8jRZs1i-t42gxIWIrKyOKoujy886Ck

###
PATCH http://localhost:3001/api/posts/6542fb3a5d8ae90b8502b163/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2E0YWZkODVhZjFhYmE2ODY1YjY0YSIsImlhdCI6MTY5OTIyNDc0NiwiZXhwIjoxNjk5NDgzOTQ2fQ.EOyux8qRDvxHyrnZEL45sY-HrqsRcGmRSxCSQar5yMs
content-type: application/json

{
    "text": "Test comment 5 777777777777777777777777777777777777777777777777777777777777777777"
}

###
DELETE http://localhost:3001/api/posts/6556d6109fe74e96be63f2b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiNGY3OTczOGNiODkyNWFlYmExNiIsImlhdCI6MTcwMDA1NTMyMCwiZXhwIjoxNzAwMjI4MTIwfQ.BDqx28DEdibedthKArUlQIasj-3n6TXtmyZJkqNsyWk

###
DELETE http://localhost:3001/api/posts/6556d6109fe74e96be63f2b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTBiNGY3OTczOGNiODkyNWFlYmExNiIsImlhdCI6MTcwMDA1NTMyMCwiZXhwIjoxNzAwMjI4MTIwfQ.BDqx28DEdibedthKArUlQIasj-3n6TXtmyZJkqNsyWk

###
PATCH  http://localhost:3001/api/posts/655a2f04c3f95d52495cd655
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMDM3Mzk4OSwiZXhwIjoxNzAwNTQ2Nzg5fQ.6bFMuEv5Ke3iy-ucoCAmrU2DXMsB8_CdPTGDeI2EFCE
content-type: application/json

{
    "content": "new content 2"
}

###
GET http://localhost:3001/api/chats/6550b31b9738cb8925aeb966
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMjE4MDk0NCwiZXhwIjoxNzAyMzUzNzQ0fQ.9EJI9inW0jwMGpXoraGmTn5xCSiM62cr-CPi3NWDq_E

###
POST http://localhost:3001/api/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMjE4MDk0NCwiZXhwIjoxNzAyMzUzNzQ0fQ.9EJI9inW0jwMGpXoraGmTn5xCSiM62cr-CPi3NWDq_E
content-type: application/json

{
    "message": "message 3",
    "recipient": "655974b5aa661554a4e17eb5"
}

###
POST http://localhost:3001/api/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTk3NGI1YWE2NjE1NTRhNGUxN2ViNSIsImlhdCI6MTcwMjE4MDk0NCwiZXhwIjoxNzAyMzUzNzQ0fQ.9EJI9inW0jwMGpXoraGmTn5xCSiM62cr-CPi3NWDq_E
content-type: application/json

{
    "message": "message to unrelated",
    "recipientId": "6550b43c9738cb8925aeb9da"
}

